nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - ia32
    - arm
    - arm64
    - mips
    - mipsel
    - ppc
    - ppc64
    - riscv64
    - s390
    - s390x
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - linux
    - windows
    - darwin

yarnPath: .yarn/releases/yarn-4.1.0.cjs
