steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/hmm-dev/me:latest || exit 0"]

  - name: "gcr.io/cloud-builders/docker"
    args: [
        "build",
        "-t",
        "gcr.io/hmm-dev/me:latest",
        "--build-arg",
        "COMMIT_SHA=${COMMIT_SHA}",
        "--cache-from=gcr.io/hmm-dev/me:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "tag"
      - "gcr.io/hmm-dev/me:latest"
      - "gcr.io/hmm-dev/me:$COMMIT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/hmm-dev/me:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/hmm-dev/me:latest"]

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/me'
      - '--namespace=me'
      - 'me=gcr.io/hmm-dev/me:$COMMIT_SHA'
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=hmm"

images:
  - "gcr.io/hmm-dev/me:$COMMIT_SHA"
  - "gcr.io/hmm-dev/me:latest"
timeout: 720s