version: 2.1

jobs:
  build-web:
    working_directory: ~/me
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-web-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "web/yarn.lock" }}
            - v2-web-dependencies

      - run:
          name: Installing root dependencies
          command: yarn install

      - run:
          name: Installing web dependencies
          command: yarn --cwd web install

      - run:
          name: Run front end web tests
          command: yarn test:web

      - run:
          name: Build bundle and all assets
          command: yarn build:web

      - save_cache:
          paths:
            - node_modules
            - web/node_modules
          key: v2-web-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "web/yarn.lock" }}

      - run:
          name: Clean up workspace
          command: rm -rf web/node_modules

      - persist_to_workspace:
          root: ./
          paths:
            - ./

  deploy-web:
    working_directory: ~/me
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./

      - run:
          name: Upload production web bundle to S3 and invalidate CloudFront distribution
          command: yarn deploy:web

  deploy-api:
    working_directory: ~/me
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-api-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "api/yarn.lock" }}
            - v2-api-dependencies

      - run:
          name: Installing API dependencies
          command: yarn --cwd api install

      - run:
          name: Deploying API
          command: yarn --cwd api deploy:prod

      - save_cache:
          paths:
            - node_modules
            - api/node_modules
          key: v2-api-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "api/yarn.lock" }}

workflows:
  version: 2
  me:
    jobs:
      - build-web:
          context: maingot

      - deploy-web:
          context: maingot
          requires:
            - build-web
          filters:
            branches:
                only: master

      - deploy-api:
          context: maingot
          requires:
            - build-web
          filters:
            branches:
                only: master
