service:
  name: me-api
  app: me

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  meeting-availability:
    handler: handler.availability
    events:
      - http:
          method: get
          path: meeting/{duration}/availability
          cors: true

  meeting-schedule:
    handler: handler.schedule
    events:
      - http:
          method: post
          path: meeting/{duration}/schedule
          cors: true


custom:
  serverless-offline:
    port: 3001
