service:
  name: me-api
  app: me
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  tracing:
    apiGateway: true
    lambda: true
  logs:
    restApi:
      level: INFO
      executionLogging: true
      fullExecutionData: true
    frameworkLambda: true
  individually: true
  memorySize: 128
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    - 'arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess'
  environment:
    AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
    MEETING_15M_ID: ${self:custom.secrets.MEETING_15M_ID}
    MEETING_30M_ID: ${self:custom.secrets.MEETING_30M_ID}
    MEETING_1HR_ID: ${self:custom.secrets.MEETING_1HR_ID}
    AVAILABILITY_ENDPOINT: ${self:custom.secrets.AVAILABILITY_ENDPOINT}
    CREATE_MEETING_ENDPOINT: ${self:custom.secrets.CREATE_MEETING_ENDPOINT}

functions:
  meeting-availability:
    handler: src/availability.handler
    events:
      - http:
          method: get
          path: meeting/{duration}/availability
          cors:
            origins:
              - https://hmm.dev

  meeting-schedule:
    handler: src/schedule.handler
    events:
      - http:
          method: post
          path: meeting/{duration}/schedule
          cors:
            origins:
              - https://hmm.dev

custom:
  serverless-offline:
    port: 3001
  secrets: ${ssm:/aws/reference/secretsmanager/${env:AWS_SECRET_NAME}~true}