service:
  name: me-api
  app: me

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x

functions:
  meeting-availability:
    handler: handler.availability
    events:
      - http:
          method: get
          path: meeting/{duration}/availability
          cors: true
    environment:
      15M_MEETING_ID: ${self:custom.secrets.15M_MEETING_ID}
      30M_MEETING_ID: ${self:custom.secrets.30M_MEETING_ID}
      1HR_MEETING_ID: ${self:custom.secrets.1HR_MEETING_ID}
      AVAILABILITY_ENDPOINT: ${self:custom.secrets.AVAILABILITY_ENDPOINT}

  meeting-schedule:
    handler: handler.schedule
    events:
      - http:
          method: post
          path: meeting/{duration}/schedule
          cors: true
    environment:
      15M_MEETING_ID: ${self:custom.secrets.15M_MEETING_ID}
      30M_MEETING_ID: ${self:custom.secrets.30M_MEETING_ID}
      1HR_MEETING_ID: ${self:custom.secrets.1HR_MEETING_ID}
      CREATE_MEETING_ENDPOINT: ${self:custom.secrets.CREATE_MEETING_ENDPOINT}

custom:
  serverless-offline:
    port: 3001
  secrets: ${ssm:/aws/reference/secretsmanager/${env:AWS_SECRET_NAME}~true}