service:
  name: me-api
  app: me
  tracing: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs10.x

functions:
  meeting-availability:
    handler: handler.availability
    tracing: true
    events:
      - http:
          method: get
          path: meeting/{duration}/availability
          cors:
            origins:
              - https://hmm.dev
    environment:
      MEETING_15M_ID: ${self:custom.secrets.MEETING_15M_ID}
      MEETING_30M_ID: ${self:custom.secrets.MEETING_30M_ID}
      MEETING_1HR_ID: ${self:custom.secrets.MEETING_1HR_ID}
      AVAILABILITY_ENDPOINT: ${self:custom.secrets.AVAILABILITY_ENDPOINT}

  meeting-schedule:
    handler: handler.schedule
    tracing: true
    events:
      - http:
          method: post
          path: meeting/{duration}/schedule
          cors:
            origins:
              - https://hmm.dev
    environment:
      MEETING_15M_ID: ${self:custom.secrets.MEETING_15M_ID}
      MEETING_30M_ID: ${self:custom.secrets.MEETING_30M_ID}
      MEETING_1HR_ID: ${self:custom.secrets.MEETING_1HR_ID}
      CREATE_MEETING_ENDPOINT: ${self:custom.secrets.CREATE_MEETING_ENDPOINT}

custom:
  serverless-offline:
    port: 3001
  secrets: ${ssm:/aws/reference/secretsmanager/${env:AWS_SECRET_NAME}~true}